# Generated by Django 4.2 on 2023-04-17 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_auther",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_special",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
