# Generated by Django 4.2 on 2023-04-17 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_is_auther_user_is_special"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_auther",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_special",
        ),
        migrations.AddField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(default=False, verbose_name="وضعیت نویسندگی"),
        ),
        migrations.AddField(
            model_name="user",
            name="special_user",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="کاربر ویژه تا"
            ),
        ),
    ]
