# Generated by Django 4.2 on 2023-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haminjory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("d", "Draft"), ("p", "published")], max_length=1
            ),
        ),
    ]
