# Generated by Django 4.2 on 2023-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haminjory", "0002_alter_article_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("status", models.BooleanField(default=True)),
                ("position", models.IntegerField()),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "مقاله", "verbose_name_plural": "مقاله ها "},
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
    ]
